### ISSUE TITLE
Semantic Versioning?

### ISSUE THREAD

**Issue by tisto** [eea/volto-accordion-block#46]
Question: does volto-accordeon-blocks use semantic versioning?

As far as I can see the latest version 3.4.14 introduced two new features:

https://github.com/eea/volto-accordion-block/compare/3.4.13...3.4.14

We are using the accordion block in our client project and two new fields mean that our editors suddenly have new configuration options. That's nice. Though, as service provider we have to make sure those new options fully work in our environment, we have to add this to our documentation, to our storybooks, etc. Semantic versioning helps us to keep track of this. Therefore my question...

**Comment by nileshgulia1** [comment]
@tisto We have a  CI server that automatically builds, tests, tags and outputs an incremented "patch" versioned package when it comes to addons that is used by EEA projects.  For non-backward compatible changes, the "major" version has to be incremented by hand or using "release-it". 

But yes in any case, those versions can be overridden by user before merging (hence releasing) PR to master.
 
IIRC, We had faced problems regarding automated releases with versions conflicting in JENKINS and release-it package, maybe @valentinab25  knows more.

For projects we usually cut "minor" version "automatic releasing", and a major version by hand.

**Comment by avoinea** [comment]
@tisto Sorry for that. Razvan pushed the merge button and the CI/CD automatically released it as minor.

**Comment by avoinea** [comment]
@tisto Unfortunately we can't unpublish 3.4.14 anymore as other packages were release with it as dependency https://github.com/eea/volto-eea-kitkat/releases

**Comment by razvanMiu** [comment]
`3.4.14` has no impact for editors, it doesn't modify the ui, it only adds two configuration settings for customizing the icons (for developers).
* You can customize `config.blocks.blocksConfig.accordion.titleIcons.size` from a theme addon to specify the size of the icons (default: `24px`)
* You can set `config.blocks.blocksConfig.accordion.titleIcons.semanticIcon` with a semantic icon name like 'dropdown' to use semantic icons instead of pastanaga icons (dafault: `undefined`)
